
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - --fix
          # - --unsafe-fixes
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-actions
