codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 70..80
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

parsers:
  gcov:
    branch_detections:
      conditional: yes
      loop: yes
      method: no
      macro: no
