name: Hello GH Actions 🌍

on:
    push:

jobs:
  Hello-world:
    runs-on: ubuntu-latest  # Отступ: 2 пробела от `jobs`
    steps:
      - name: My first step
        run: echo "Hello action!"  # Отступ: 4 пробела от `steps`
